### ISSUE TITLE
Include as a default plugin

### ISSUE THREAD

**Issue by brianjmurrell** [EionRobb/pidgin-paste-image#1]
Any plans here to upstream this is whatever way is necessary so that this is part of the default set of plugins for pidgin?

**Comment by EionRobb** [comment]
I'd probably do it differently if it were upstreamed and fix up the paste code directly in Pidgin instead, rather than this giant hack 😄 . I dont think grim is accepting any patches for pidgin2 though, so unlikely to be merged. 

Sadly going to go with a "no" on this one 😕
